language: node_js
node_js:
- '10'
before_script:
  - npx npm-install-peers
script: 
  - npm run lint
  - npm run build
  - npm run docs && touch docs/.nojekyll
deploy:
  - provider: pages
    github-token:
      secure: "zdWCYG1xP86XfSmSQRorf7Phu9t65Pih7yQwfejSV1Tkrpaa8VX/o5RVg37d6x0onurK2cqr2ERLq2iESvuW8Dt0has0eetbz6aPf5qd7NhPJenNyFVu74qJr/oG/pGZNmk6uCcoRb2/OVn8Vr5MoDiSpZtpCvoePSxmgstVdKwGAdWCxDRsg8UqDINQmv+ZH8EphRfDUdRQ5gi0DlTEcoMePQmELZ7qmN36u7EiE20DKvN4rpyl0kftmSBpzE3ghNBCch01TxYrobqnr4Bz+4B5AVZb+/om7iT7wMarco2oSt+3iyPGtk2vBjywso92BDJbM2VLE94EOUxPuFgVyBRsuzrUif2kWslH4R9/bIUtTUiBGfwS5BQytf3Dx+L6OwqgGNEe2ep2/GVc54mi/Uf2kckAL3zGcv62nDV0XXiKXwV5+ggFoyATK8CTEL6IcUJTU7wxjqrjNFYX0Va7gW68uXBEsDyLDP//x1oCeA7i2CvmJM0Go79/va8RJ9PFK+0qRjrYiZ6I37rE73Qhx5EEO4rm1hu4NUz7eqLnmeG9gh4Zth338gJooTWubf6MdRjbMkWnpH8PIC9tAKBSXQjs6aqo0bRhSe287tfp4d/jeEtrUB80uOszxeXvKEMiEUilmVpQiTqbB+43acsFkH2RYNmYFqndycY+z2ue8hI="
    local-dir: './docs'
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: "lee55962698@gmail.com"
    api_key: 
      secure: "eHGo8NYMJfJrTXtAdbAP+jUltPfS8TGTcat8SrjhBTBL82V39Ml29GtSwM7GPGnGjDotjb8BnDMJxkzf+rsJW69hfWmlpjNNoYTASphK5Tc590O5z95E1WTrG/86VARDiGU6QlJ/fN0CB+BawS5/zQJnhsHAjRm0oKv0L5Ynqcu3GFdhGK+IWENltEL+3UziLzzal0oT2Cejh5d68R5/6/6mQNOSx+kmOhDDoPeLCLWTkaSyYyOsHcViaMmpXsAOHIqnYrNhln7GLxJ8uz+oYCc2gF5tVMOh5iH7ANpkKdxGJqwu6Rb7bMdncuZJ7RXMVrVzbSy3S/RBmxOSZFmcAlDB/WE+gg+dnacmFTbrkxbXhTnTs13BJw8VO7sdWWTjwA9D/5TIUW7/bOBHswRHVvsueeI1mohBvsAchtMcUYADmfwr1cwY9h9L0XlKlYAI5qPNF6Im3PJmCLX0w01jEAYQswTcJq5ypOZzS1CDPETRDB8kED7sRNlxyhG7JsTj/MeZBQOm6shgpijJsBE3UoxffsSj4DkAdUnUZCcnHQLv5nUIHJdqJab6QV9NcqQ7x8x6hlnuW7ziP4HzNAj8W6nX18H2z7NdhZ4EJo8XeyjM4HgpueglxYKvmIUuSI7UW7hh1nnyrq84g4e7uNKLISL2+ZkMAj36q5gRpwpSbkE="
    skip_cleanup: true
    on:
      tags: true
